import type {
  Address,
  DeliveryOrder,
  NearbyVehicleView,
  OrderStatusEvent,
  PricingPolicy,
  Quote,
  User,
  Vehicle,
  VehicleAvailabilityRule,
  VehicleModel,
  VehicleOwner,
} from "./types";

const NOW = "2026-09-21T09:41:00+08:00";

export const mockUsers: User[] = [
  {
    id: "usr_customer_001",
    nickname: "微信用户",
    roles: ["customer", "vehicle_owner"],
    status: "active",
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const mockAddresses: Address[] = [
  {
    id: "addr_library",
    userId: "usr_customer_001",
    label: "school",
    name: "江西师范大学（瑶湖校区）图书馆",
    contactName: "测试用户",
    contactMobile: "138****0000",
    regionCode: "360111",
    detail: "江西师范大学瑶湖校区图书馆",
    location: { latitude: 28.6829, longitude: 115.8582 },
    isDefaultSender: true,
    isDefaultReceiver: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "addr_stadium_east",
    userId: "usr_customer_001",
    label: "school",
    name: "瑶湖体育场东门",
    contactName: "测试用户",
    contactMobile: "138****0000",
    regionCode: "360111",
    detail: "瑶湖体育场东门",
    location: { latitude: 28.6841, longitude: 115.8711 },
    isDefaultSender: false,
    isDefaultReceiver: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const mockVehicleOwner: VehicleOwner = {
  id: "owner_001",
  userId: "usr_customer_001",
  subjectType: "individual",
  displayName: "测试车主",
  verificationStatus: "verified",
  createdAt: NOW,
  updatedAt: NOW,
};

export const mockVehicleModels: VehicleModel[] = [
  {
    id: "model_box_small",
    code: "XC-02",
    name: "小型厢式无人车",
    category: "box_small",
    imageUrl: "/assets/vehicles/box-small.png",
    maxLoadGrams: 100000,
    cargoVolumeLiters: 1200,
    energyType: "electric",
    supportsColdChain: false,
    supportedCargoCategories: ["general", "document", "food", "medical", "other"],
    enabled: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "model_box_medium",
    code: "XC-05",
    name: "中型厢式无人车",
    category: "box_medium",
    imageUrl: "/assets/vehicles/box-medium.png",
    maxLoadGrams: 300000,
    cargoVolumeLiters: 4000,
    energyType: "electric",
    supportsColdChain: false,
    supportedCargoCategories: ["general", "document", "food", "medical", "other"],
    enabled: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "model_cold_chain",
    code: "CC-02",
    name: "冷链无人车",
    category: "cold_chain",
    imageUrl: "/assets/vehicles/cold-chain.png",
    maxLoadGrams: 200000,
    cargoVolumeLiters: 2500,
    energyType: "electric",
    supportsColdChain: true,
    supportedCargoCategories: ["fresh_cold_chain", "food", "medical"],
    enabled: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: "veh_001",
    vehicleNo: "CLY-NC-001",
    modelId: "model_box_small",
    ownerId: "owner_001",
    serviceRegionId: "region_yaohu",
    status: "available",
    location: { latitude: 28.6852, longitude: 115.8612 },
    locationUpdatedAt: NOW,
    batteryPercent: 78,
    remainingRangeMeters: 35000,
    imageUrls: ["/assets/vehicles/box-small.png"],
    enabled: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "veh_002",
    vehicleNo: "CLY-NC-002",
    modelId: "model_box_medium",
    ownerId: "owner_001",
    serviceRegionId: "region_yaohu",
    status: "available",
    location: { latitude: 28.6804, longitude: 115.8635 },
    locationUpdatedAt: NOW,
    batteryPercent: 65,
    remainingRangeMeters: 28000,
    imageUrls: ["/assets/vehicles/box-medium.png"],
    enabled: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "veh_003",
    vehicleNo: "CLY-NC-003",
    modelId: "model_cold_chain",
    ownerId: "owner_001",
    serviceRegionId: "region_yaohu",
    status: "available",
    location: { latitude: 28.6778, longitude: 115.8501 },
    locationUpdatedAt: NOW,
    batteryPercent: 82,
    remainingRangeMeters: 42000,
    imageUrls: ["/assets/vehicles/cold-chain.png"],
    enabled: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const mockAvailabilityRules: VehicleAvailabilityRule[] = [
  {
    id: "availability_veh_001",
    vehicleId: "veh_001",
    timezone: "Asia/Shanghai",
    ranges: [{ weekdays: [1, 2, 3, 4, 5, 6, 7], startTime: "08:00", endTime: "22:00" }],
    enabled: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const mockNearbyVehicles: NearbyVehicleView[] = [
  {
    vehicle: mockVehicles[0],
    model: mockVehicleModels[0],
    distanceToUserMeters: 320,
    estimatedArrivalMinutes: 4,
    recommended: true,
    recommendationTags: ["适合当前物品", "性价比高"],
  },
  {
    vehicle: mockVehicles[1],
    model: mockVehicleModels[1],
    distanceToUserMeters: 580,
    estimatedArrivalMinutes: 6,
    recommended: false,
    recommendationTags: ["空间更大", "适合大件"],
  },
  {
    vehicle: mockVehicles[2],
    model: mockVehicleModels[2],
    distanceToUserMeters: 1200,
    estimatedArrivalMinutes: 8,
    recommended: false,
    recommendationTags: ["冷藏保鲜", "温控运输"],
  },
];

export const mockPricingPolicy: PricingPolicy = {
  id: "pricing_district_001",
  name: "瑶湖校区标准配送价格",
  scope: "district",
  regionId: "region_yaohu",
  version: 1,
  minimumOrderAmountFen: 500,
  maximumOrderAmountFen: 1500,
  baseFeeFen: 500,
  includedDistanceMeters: 0,
  extraDistanceFeeFenPerKm: 200,
  effectiveFrom: "2026-09-01T00:00:00+08:00",
  enabled: true,
  createdAt: "2026-09-01T00:00:00+08:00",
  updatedAt: "2026-09-01T00:00:00+08:00",
};

export const mockQuote: Quote = {
  id: "quote_001",
  orderDraftKey: "draft_local_001",
  customerId: "usr_customer_001",
  vehicleId: "veh_001",
  vehicleModelId: "model_box_small",
  pricingPolicyId: "pricing_district_001",
  pricingPolicyVersion: 1,
  routeDistanceMeters: 1300,
  estimatedArrivalMinutes: 4,
  items: [
    { type: "base_fee", label: "基础运费", amountFen: 500 },
    { type: "distance_fee", label: "里程费（约1.3km）", amountFen: 260 },
  ],
  totalAmountFen: 760,
  expiresAt: "2026-09-21T09:46:00+08:00",
  createdAt: NOW,
  updatedAt: NOW,
};

export const mockOrder: DeliveryOrder = {
  id: "order_001",
  orderNo: "CLY202609210001",
  type: "task_delivery",
  customerId: "usr_customer_001",
  serviceRegionId: "region_yaohu",
  sender: {
    sourceAddressId: "addr_library",
    name: "江西师范大学（瑶湖校区）图书馆",
    contactName: "测试用户",
    contactMobile: "138****0000",
    regionCode: "360111",
    detail: "江西师范大学瑶湖校区图书馆",
    location: { latitude: 28.6829, longitude: 115.8582 },
  },
  receiver: {
    sourceAddressId: "addr_stadium_east",
    name: "瑶湖体育场东门",
    contactName: "测试用户",
    contactMobile: "138****0000",
    regionCode: "360111",
    detail: "瑶湖体育场东门",
    location: { latitude: 28.6841, longitude: 115.8711 },
  },
  cargo: {
    category: "document",
    description: "文件5份",
    quantity: 1,
    unitWeightGrams: 500,
    unitDimensionsMm: { length: 300, width: 200, height: 100 },
    fragile: false,
    needsHandling: false,
  },
  serviceTimeMode: "immediate",
  vehicleSnapshot: {
    vehicleId: "veh_001",
    vehicleModelId: "model_box_small",
    vehicleNo: "CLY-NC-001",
    modelName: "小型厢式无人车",
    imageUrl: "/assets/vehicles/box-small.png",
    maxLoadGrams: 100000,
    cargoVolumeLiters: 1200,
    batteryPercent: 78,
  },
  assignedVehicleId: "veh_001",
  acceptedQuoteId: "quote_001",
  totalAmountFen: 760,
  status: "vehicle_to_pickup",
  estimatedPickupAt: "2026-09-21T09:45:00+08:00",
  estimatedDeliveryAt: "2026-09-21T09:55:00+08:00",
  createdAt: NOW,
  updatedAt: NOW,
};

export const mockOrderEvents: OrderStatusEvent[] = [
  {
    id: "event_001",
    orderId: "order_001",
    toStatus: "pending_payment",
    actorType: "customer",
    actorId: "usr_customer_001",
    occurredAt: "2026-09-21T09:40:00+08:00",
    note: "用户确认订单",
    createdAt: "2026-09-21T09:40:00+08:00",
    updatedAt: "2026-09-21T09:40:00+08:00",
  },
  {
    id: "event_002",
    orderId: "order_001",
    fromStatus: "pending_payment",
    toStatus: "paid",
    actorType: "system",
    occurredAt: "2026-09-21T09:40:10+08:00",
    note: "模拟支付成功",
    createdAt: "2026-09-21T09:40:10+08:00",
    updatedAt: "2026-09-21T09:40:10+08:00",
  },
  {
    id: "event_003",
    orderId: "order_001",
    fromStatus: "paid",
    toStatus: "matching",
    actorType: "system",
    occurredAt: "2026-09-21T09:40:15+08:00",
    note: "系统正在匹配附近可用车辆",
    createdAt: "2026-09-21T09:40:15+08:00",
    updatedAt: "2026-09-21T09:40:15+08:00",
  },
  {
    id: "event_004",
    orderId: "order_001",
    fromStatus: "matching",
    toStatus: "dispatched",
    actorType: "system",
    occurredAt: "2026-09-21T09:40:30+08:00",
    note: "已匹配车辆 CLY-NC-001",
    createdAt: "2026-09-21T09:40:30+08:00",
    updatedAt: "2026-09-21T09:40:30+08:00",
  },
  {
    id: "event_005",
    orderId: "order_001",
    fromStatus: "dispatched",
    toStatus: "vehicle_to_pickup",
    actorType: "vehicle",
    actorId: "veh_001",
    occurredAt: NOW,
    note: "车辆正在前往取件点",
    createdAt: NOW,
    updatedAt: NOW,
  },
];
